version: '3'
services:
  db:
    image: postgres:alpine    
    ports:
      - "5432:5432"
    expose:
      - "5432"    
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./scripts:/docker-entrypoint-initdb.d"
